(defpackage #:com.inuoe.seqio
  (:use
   #:alexandria
   #:cl)
  (:import-from
   #:com.inuoe.seq
   #:col-seq
   #:mapcol
   #:seq-first
   #:seq-rest
   #:lazy-seq)
  (:export
   ;;;grouping-col
   #:grouping-col
   #:grouping-col-key
   #:grouping-col-seq
   #:make-grouping-col

   ;;ordered-col
   #:ordered-col
   #:ordered-col-seq
   #:ordered-col-comparer
   #:make-ordered-col

   ;;;seq expressions
   #:aggregate
   #:aggregate*
   #:all
   #:any
   #:any*
   #:eappend
   #:batch
   #:concat
   #:consume
   #:contains
   #:ecount
   #:ecount*
   #:default-if-empty
   #:distinct
   #:element-at
   #:evaluate
   #:empty
   #:except
   #:efirst
   #:efirst*
   #:group-adjacent
   #:group-by
   #:intersect
   #:elast
   #:elast*
   #:order-by
   #:order-by-descending
   #:prepend
   #:range
   #:repeat
   #:ereverse
   #:run-length-encode
   #:select
   #:select*
   #:select-many
   #:select-many*
   #:single
   #:single*
   #:skip
   #:skip-last
   #:skip-until
   #:skip-while
   #:take
   #:take-every
   #:take-last
   #:take-until
   #:take-while
   #:then-by
   #:then-by-descending
   #:eunion
   #:where
   #:window
   #:to-hash-table
   #:to-list
   #:to-vector))
